// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eBookStore.API.Book.Persistence;

namespace eBookStore.API.Book.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221125163649_Initiall")]
    partial class Initiall
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eBookStore.API.Book.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Name = "To Kill a Mockingbird",
                            Price = 5m
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Name = "The Great Gatsby",
                            Price = 5m
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Name = "One Hundred Years of Solitude",
                            Price = 5m
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Name = "A Passage to India",
                            Price = 5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
