version: '3.4'

services:
  ebookstore.db:
    container_name: "ebookstore.db"
    image: "mcr.microsoft.com/mssql/server:latest"
    volumes:
    - sqlvolume:/var/opt/mssql    
    environment:
      SA_PASSWORD: "Admin123."
      ACCEPT_EULA: "Y"
    ports:
    - 1433:1433
    networks:
    - eBookStore

  ebookstore.rabbitmq:
    container_name: "ebookstore.rabbitmq"
    image: rabbitmq:management
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    ports:      
      - 5672:5672   # AMQP protocol port      
      - 15672:15672 # HTTP management UI
    networks:
    - eBookStore
    volumes:
    - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

networks:
  eBookStore:
    name: eBookStore
    driver: bridge

volumes:
  sqlvolume:
  rabbitmqdata: