version: '3.4'

services:
  ebookstore.api.author:
    image: ${DOCKER_REGISTRY-}ebookstore.api.author
    container_name: ebookstore.api.author
    build:
      context: .
      dockerfile: eBookStore.API.Author/Dockerfile
    restart: on-failure
    networks:
      - eBookStore
    depends_on:
      - ebookstore.db
      - ebookstore.rabbitmq

  ebookstore.api.book:
    image: ${DOCKER_REGISTRY-}ebookstore.api.book
    container_name: ebookstore.api.book
    build:
      context: .
      dockerfile: eBookStore.API.Book/Dockerfile
    restart: on-failure
    networks:
      - eBookStore
    depends_on:
      - ebookstore.db
      - ebookstore.rabbitmq

  ebookstore.api.basket:
    image: ${DOCKER_REGISTRY-}ebookstore.api.basket
    container_name: ebookstore.api.basket
    build:
      context: .
      dockerfile: eBookStore.API.Basket/Dockerfile
    restart: on-failure
    networks:
      - eBookStore
    depends_on:
      - ebookstore.db
      - ebookstore.rabbitmq
      
  ebookstore.api.gateway:
    image: ${DOCKER_REGISTRY-}ebookstore.api.gateway
    container_name: ebookstore.api.gateway
    build:
      context: .
      dockerfile: eBookStore.API.Gateway/Dockerfile
    networks:
      - eBookStore
    depends_on:
    - ebookstore.api.book
    - ebookstore.api.author
    - ebookstore.api.basket
      
  ebookstore.db:    
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: ebookstore.db
    volumes:
    - sqlvolume:/var/opt/mssql    
    environment:
      SA_PASSWORD: "Admin123."
      ACCEPT_EULA: "Y"
    networks:
      - eBookStore

  ebookstore.rabbitmq:    
    image: rabbitmq:management
    container_name: ebookstore.rabbitmq
    networks:
      - eBookStore
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

networks:
  eBookStore:
    name: eBookStore
    driver: bridge

volumes:
  sqlvolume:
  rabbitmqdata: